config/routes.rb
Rails.application.routes.draw do
  resources :books

  devise_for :users
  mount RailsAdmin::Engine => '/book', as: 'rails_admin'
  

  get 'home/about'

  get 'home/contact'

  root 'home#index'

 

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def category_enum
   	[['0level'],['Alevel'],['Other']]
  end
  validates_presence_of :title, :price,:description
  #validates_uniqueness_of :childID
  validates :price, :numericality => { :greater_than_or_equal_to => -1, :less_than_or_equal_to => 1000000000 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json
  def index
    @books = Book.all
    respond_with(@books)
  end

  def show
    respond_with(@book)
  end

  def new
    @book = Book.new
    respond_with(@book)
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    @book.save
    respond_with(@book)
  end

  def update
    @book.update(book_params)
    respond_with(@book)
  end

  def destroy
    @book.destroy
    respond_with(@book)
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :description, :price, :category)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@books = Book.order("title").page(params[:page]).per(1)
  end

  def about
  end

  def contact
  	# @ministry = Home.where(category: 'ministry').last(3)
  	# @achievement = Home.where(category: 'homenews').last(6)
  	# @event = Home.where(category: 'Workinprogress').last(3)
  	# # @advert = Home.where(category: 'advert').last(1)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.price %></td>
        <td><%= book.category %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @book.category %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/home/index.html.erb
<section id="advertisement">
	<div class="container">
		<img src="" alt="" />
	</div>
</section>

<section>
	<div class="container">
		<div class="row">
			<div class="col-sm-3">
				<div class="left-sidebar">
					<h2>Category</h2>
					<div class="panel-group category-products" id="accordian"><!--category-productsr-->
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a data-toggle="collapse" data-parent="#accordian" href="#sportswear">
										<span class="badge pull-right"><i class="caret"></i></span>
										Inspirations
									</a>
								</h4>
							</div>
							<div id="sportswear" class="panel-collapse collapse">
								<div class="panel-body">
									<ul>
										<li><a href="">Seven laws of success </a></li>
										<li><a href="">Never give up</a></li>
										
									</ul>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a data-toggle="collapse" data-parent="#accordian" href="#mens">
										<span class="badge pull-right"><i class="caret"></i></span>
										A level books
									</a>
								</h4>
							</div>
							<div id="mens" class="panel-collapse collapse">
								<div class="panel-body">
									<ul>
										<li><a href="">Concise Math</a></li>
										<li><a href="">Tranta</a></li>
										<li><a href="">Understanding mechanics</a></li>
										<li><a href="">Pure Math</a></li>
										
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>		

			</div>

			<div class="col-sm-9 padding-right">
				<div class="features_items"><!--features_items-->
					<h2 class="title text-center">Features Books</h2>
					<%@books.each_slice(3) do |book|%>
					<%book.each do |bk|%>
					<div class="col-sm-4">
						<div class="product-image-wrapper">
							<div class="single-products">
								<div class="productinfo text-center">
									<%= image_tag bk.avatar.url %>
									<h2>SHS:<%=bk.price %></h2>
									<p><%=bk.description %></p>
									
								</div>
								<div class="product-overlay">
									<div class="overlay-content">
										<h2>SHS:<%=bk.price %></h2>
										<p><%=bk.description %></p>
										<a href="#" class="btn btn-default add-to-cart"><i class=""></i>Make your order</a>
									</div>
								</div>
							</div>
							
						</div>
					</div>

					<% end %>
					<% end %>
			</div>
		</div>
	</div>
</section>
<%= paginate @books %>

			

app/views/layouts/_footer.html.erb
<div class="container">
	<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
		<div class="container">
			<ul class="nav navbar-nav">
				<li class="pull-right	"><a href="#">Copyright <%=Time.now %></a></li>
				<li class=""><a href="#"></a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
            	<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					Coming Soon <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><a href="#">New books</a></li>
						<li><a href="#">Check out our stationery</a></li>
					</ul>
				</li>
          	</ul>
		</div>
	</nav>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">BOOK SHOP</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", home_about_path %></li>
            <li><%= link_to "Contact", home_contact_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Book category1"%></li>
                <li><%= link_to "Book category2" %></li>
                <li class="divider"></li>
                <li><%= link_to "Book category3" %></li>
                <li><%= link_to "Book category4" %></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => "delete" %></li>
              <li><%= link_to "View orders" %></li>
            <% else %>
              <li><%= link_to "Sign in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div style="margin-top:60px;">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Book Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style type="text/css">
  	body{color:black;}
  	p{font-size: 10px;}
  	a{color:pink;}
  </style>

</head>
<body>
<%= render :partial => "layouts/header"%>
<div class="container">
	<%= yield %>
</div>
<%= render :partial => "layouts/footer"%>

</body>
</html>